package com.example.uts_mcs;

import android.content.Intent;
import android.os.Bundle;

import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.Toast;

import java.util.ArrayList;

public class HomeFragment extends Fragment {

    RecyclerView recyclerViewNews, recyclerViewGallery, recyclerViewMatches;
    ArrayList<gallery> galleryArrayList = new ArrayList<>();
    ArrayList<news> newsArrayList = new ArrayList<>();
    ArrayList<matches> matchesArrayList = new ArrayList<>();
    AdapterMatchData adapterMatch;
    AdapterNewsData adapterNews;
    AdapterGalleryData adapterGallery;
    ImageView logout;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_home, container, false);
        
        logout = view.findViewById(R.id.logoutIc);
        logout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Toast.makeText(getActivity(), "Logout Success", Toast.LENGTH_SHORT).show();
                startActivity(new Intent(getActivity(), LoginActivity.class));
            }
        });

        recyclerViewGallery = view.findViewById(R.id.rv_gallery);
        recyclerViewGallery.setLayoutManager(new LinearLayoutManager(this.getContext(), LinearLayoutManager.HORIZONTAL, false));
        adapterGallery = new AdapterGalleryData(this.getContext(), galleryArrayList);
        recyclerViewGallery.setAdapter(adapterGallery);

        galleryArrayList.add(new gallery(R.drawable.england_train, "GALLERY", "Kane, Dier and Foster train with England", "21 Mar, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        galleryArrayList.add(new gallery(R.drawable.th_vs_everton, "GALLERY", "Everton 1 - 1 Spurs", "04 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        galleryArrayList.add(new gallery(R.drawable.train_against_brighton, "GALLERY", "Squad trains against Brighton", "06 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        galleryArrayList.add(new gallery(R.drawable.vs_brighton, "GALLERY", "Spurs 2 - 1 Brighton", "08 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        galleryArrayList.add(new gallery(R.drawable.vs_bou, "GALLERY", "Players prepare for Bournemouth", "14 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        galleryArrayList.add(new gallery(R.drawable.spurs_vs_bourne, "GALLERY", "Spurs 2 - 3 AFC Bournemouth", "15 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        galleryArrayList.add(new gallery(R.drawable.masson_training, "GALLERY", "Mason takes training session", "25 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));

        recyclerViewNews = view.findViewById(R.id.rv_news);
        recyclerViewNews.setLayoutManager(new LinearLayoutManager(this.getContext(), LinearLayoutManager.VERTICAL, false));
        adapterNews = new AdapterNewsData(this.getContext(), newsArrayList);
        recyclerViewNews.setAdapter(adapterNews);
        recyclerViewNews.setHasFixedSize(true);
        recyclerViewNews.setNestedScrollingEnabled(false);

        newsArrayList.add(new news(R.drawable.ryan_masson, "NEWS", "Ryan Masson taking the training session as a coach", "26 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.rm_pri, "NEWS", "Ryan Masson : What is my priority this week? A reaction...", "27 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.mu_vs_th, "NEWS", "Five magic moments against Manchester United", "27 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.rm_pv, "NEWS", "Ryan previews United clash", "27 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.th_lineups, "NEWS", "Confirmed line-ups : Spurs vs Manchester United", "28 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.pedro_porro, "NEWS", "We made a huge mistake, but we kept working on it - Pedro Porro", "28 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.hugo_lloris, "NEWS", "Hugo Lloris out of Liverpool clash", "28 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));
        newsArrayList.add(new news(R.drawable.spurs_ladies, "NEWS", "Women's academy awarded Category 1 status", "28 Apr, 2023", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sit amet justo sit amet urna luctus dignissim ac vel arcu. Praesent vel ante leo. Nam porttitor lacus id risus rhoncus scelerisque. Duis eget lacinia metus. Suspendisse vel odio aliquam, tempor enim eu, consequat velit. Integer ut ipsum eget sapien malesuada pharetra a quis metus. Aenean pulvinar ante sit amet mi suscipit, a auctor massa commodo. Sed molestie, purus in malesuada faucibus, enim sapien commodo nisl, id fringilla urna eros vel odio. Vivamus a purus eget nunc laoreet commodo. Sed non mauris non sapien suscipit lobortis at at nunc. Quisque nec lorem rutrum, vestibulum mi in, aliquet mauris. Sed varius nunc eu nisi iaculis, at volutpat ipsum efficitur. Sed scelerisque metus odio, vel convallis nibh maximus eget.\n" +
                "\n" +
                "Morbi suscipit, libero in ullamcorper iaculis, est ligula accumsan ante, eu accumsan nisi lectus id sapien. Pellentesque posuere imperdiet felis, a ultricies elit bibendum vitae. Aliquam erat volutpat. Nam ac fringilla odio, eget laoreet mi. Sed aliquam sollicitudin diam, eu molestie velit. Fusce dictum odio nec massa bibendum ornare. Vestibulum congue ipsum velit, vel dictum enim tristique quis. Vestibulum blandit ultrices dignissim. Nullam posuere auctor mauris, sed faucibus ipsum bibendum vel. Etiam eget odio eros. Suspendisse potenti. Fusce faucibus nec ex eget vestibulum. Morbi sit amet erat ac odio bibendum aliquam. Praesent vel tincidunt ante."));

        recyclerViewMatches = view.findViewById(R.id.rv_matches);
        recyclerViewMatches.setLayoutManager(new LinearLayoutManager(this.getContext(), LinearLayoutManager.HORIZONTAL, false));
        adapterMatch = new AdapterMatchData(this.getContext(), matchesArrayList);
        recyclerViewMatches.setAdapter(adapterMatch);

        matchesArrayList.add(new matches(R.drawable.nc_logo, "23 Apr 2023 - A", "22:30 PM"));
        matchesArrayList.add(new matches(R.drawable.mu_logo, "28 Apr 2023 - H", "02:15 PM"));
        matchesArrayList.add(new matches(R.drawable.liv_logo, "30 Apr 2023 - A", "23:00 PM"));
        matchesArrayList.add(new matches(R.drawable.cp_logo, "06 May 2023 - H", "21:00 PM"));
        matchesArrayList.add(new matches(R.drawable.av_logo, "13 May 2023 - A", "21:00 PM"));
        matchesArrayList.add(new matches(R.drawable.bf_logo, "20 May 2023 - H", "18:30 PM"));
        matchesArrayList.add(new matches(R.drawable.lu_logo, "28 May 2023 - A", "22:30 PM"));

        return view;
    }
}